# \ sirve para omitir un ' en una cadena
# \n sirve para bajar una linea
# ``` sirve para escribir con espacios que sirven para bajar lineas como \n ```
#print('2' + "2") = 22 \\\\º  print( 2+2 ) = 4
# * es para multiplicar
#** es para elevar una potencia 
#print("hola" * 3)= hola hola hola
#print("2" * 3) = 222
# input() sirve para preguntar al usuario
#int() sirve para preghuntar NÚMEROS al usuario
#% sirve para el resto
#// sirve para el cociente con numeros enteros
#/ sirve para el cociente con float
#float sirve para sacar numeros con decimales
#x = x+3 se puede abreviar poniendo x+=3  (sirve con - , * / y %)
# == es un igual a
#!= no es igual a
#>= mayor o igual a
#<= menor o igual a
#
#
#
#
#
#
#